### ISSUE TITLE
Dockerfile broken by branch rename

### ISSUE THREAD

**Issue by gbhrdt** [rbenv/rbenv-installer#31]
Maybe you should add it to the readme - not sure if a branch rename is a really good idea :-).

A part of our Dockerfile looked like this:

RUN curl -sL https://github.com/rbenv/rbenv-installer/raw/master/bin/rbenv-installer | bash -

Now it looks like this, because the above command fails:

RUN curl -sL https://github.com/rbenv/rbenv-installer/raw/main/bin/rbenv-installer | bash -

**Comment by msaladna** [comment]
On that note what's the official scheme going forward within this organization? Other repos are inconsistently named at this point, specifically rbenv/rbenv-vars, rbenv/ruby-build, and rbenv/rbenv-default-gems that I checked.

**Comment by mislav** [comment]
Sorry, I thought that these links would get redirected from `master` → `main` like most other GitHub links do. I've raised an internal question into why this is not the case.

You can use `HEAD` instead of hardcoding the branch name to make sure the links always get resolved to the default branch name.

**Comment by Matt-Yorkley** [comment]
Just a heads up, I (and I assume many other people) have Ansible playbooks for provisioning that are now fatally broken by the `master` branch suddenly being a non-existent git ref in this repo. I can fix things on my end, but it was a bit of a shock!!

**Comment by mislav** [comment]
> Sorry, I thought that these links would get redirected from `master` → `main` like most other GitHub links do. I've raised an internal question at GitHub into why this is not the case.

I've got an answer from internal GitHub team: apparently these `*/raw/<branch>/<path>` links don't get the redirection treatment (like a lot of other resources do). I was counting on the redirection when I renamed the branch. Sorry everyone

**Comment by mislav** [comment]
Unrelated to all of the above, just a quick note to everyone using the rbenv-installer script in their Dockerfile: I'm pretty sure you shouldn't be using rbenv, a Ruby version manager switcher, in your containers.

rbenv was designed to switch between multiple versions of Ruby that are installed on the same machine. This was necessary because you might have several different projects that require different Ruby versions. With rbenv + bundler, each project can run isolated from each other and upgrading one can be done independently from each other.

I'm not very proficient at using containers, but I'm pretty sure that containers as a technology are also meant as a means for isolation. You can build a separate container for applications A, B, and C, where each container has its own Ruby version. If you are installing rbenv inside of your container, then I'm not really sure what you are actually using containers for in the first place. https://github.com/rbenv/rbenv-installer/commit/4a5bb5603f9da91bc24d787890ed7aafabe6e9df
